<a href="https://colab.research.google.com/github/chill-dev19/Gradient-Descent/blob/main/Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Gradient Descent is the most basic but most used optimization algorithm. It’s used heavily in linear regression and classification algorithms. It is an iterative optimisation algorithm to find the minimum of a function or find the coefficients for which the cost/loss function is minimum

Gradient descent is an optimization algorithm used to find the values of parameters (coefficients) of a function (f) that minimizes a cost function (cost). Parameters refer to coefficients in Linear Regression and weights in neural networks. Gradient Descent is a first-order optimization algorithm used to find local minima. This means it only takes into account the first derivative when performing the updates on the parameters.

#Batch Gradient Descent

BGD is a variation of the gradient descent algorithm that calculates the error for each eg in the training datasets, but only updates the model after all training examples have been evaluated.

Example:


*   Number of epochs = 10
*   Number of samples in training dataset = 50
*   Model gets updated when all 50 samples are evaluated
*   50 samples = 1; entire dataset
*   After 1 epoch 1 update takes place, After 10 epochs 10 updates takes place as given below
*   1 * 10 = 10 updates takes place in batch gradient descent

#Stochastic Gradient Descent

SGD is a variation of the gradient descent that calculates the error and updates the model for each record in the training datasets.

Example:


*   Number of epochs = 10
*   Number of samples in training dataset = 50
*   Model gets updated after every sample evaluation
*   After 1 epoch 50 updates takes place because there are 50 samples, After 10 epochs 500 updates takes place as given below
*   50 * 10 = 500 updates takes place in Stochastic gradient descent

#Mini Batch Gradient descent (MGD)

MGD is a variation of the gradient descent algorithm that splits the training datasets into small batches that are used to calculate model error and update model coefficients.

Example:


*   Number of epochs = 10
*   Number of samples in training dataset = 50
*   Each batch have 10 samples so there are total 5 batches
*   Model gets updated after every batch evaluation
*   After 1 epoch 5 updates takes place because there are 5 batches containg 10 samples each, After 10 epochs 50 updates takes place as given below
*   5 * 10 = 50 updates takes place in Mini Batch gradient descent

Order in terms of speed:
Batch gradient descent > Mini Batch gradient descent > Stochastic Gradient Descent

#Batch vs Stochastic

Batch Gradient Descent(BGD)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df = df.drop(['User ID', 'Gender'], axis=1)

In [ ]:
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [ ]:
X = df.iloc[:,0:2]

In [ ]:
Y = df.iloc[:,-1]

In [ ]:
X

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [ ]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
Scaler = StandardScaler()

In [ ]:
X = Scaler.fit_transform(X)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
import time

In [ ]:
model = Sequential()
model.add(Dense(10, activation="relu", input_dim = 2))
model.add(Dense(10, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 10)                30

 dense_4 (Dense)             (None, 10)                110

 dense_5 (Dense)             (None, 1)                 11

=================================================================
Total params: 151 (604.00 Byte)
Trainable params: 151 (604.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
X_train.shape

(320, 2)

In [ ]:
model.compile(loss = "binary_crossentropy", metrics = ['accuracy'])
start = time.time()
history = model.fit(X_train, Y_train, epochs = 100, batch_size=320, validation_split=0.2)
end = time.time()
print(end-start)

Epoch 1/100
1/1 [==============================] - 1s 894ms/step - loss: 0.6524 - accuracy: 0.7500 - val_loss: 0.6641 - val_accuracy: 0.8125
Epoch 2/100
1/1 [==============================] - 0s 36ms/step - loss: 0.6458 - accuracy: 0.7734 - val_loss: 0.6596 - val_accuracy: 0.8125
Epoch 3/100
1/1 [==============================] - 0s 36ms/step - loss: 0.6410 - accuracy: 0.7773 - val_loss: 0.6558 - val_accuracy: 0.7969
Epoch 4/100
1/1 [==============================] - 0s 36ms/step - loss: 0.6371 - accuracy: 0.7773 - val_loss: 0.6526 - val_accuracy: 0.8281
Epoch 5/100
1/1 [==============================] - 0s 60ms/step - loss: 0.6336 - accuracy: 0.7812 - val_loss: 0.6495 - val_accuracy: 0.8281
Epoch 6/100
1/1 [==============================] - 0s 40ms/step - loss: 0.6305 - accuracy: 0.7812 - val_loss: 0.6467 - val_accuracy: 0.8281
Epoch 7/100
1/1 [==============================] - 0s 36ms/step - loss: 0.6275 - accuracy: 0.7812 - val_loss: 0.6441 - val_accuracy: 0.8281
Epoch 8/100
1/1 [==============================] - 0s 37ms/step - loss: 0.6247 - accuracy: 0.7773 - val_loss: 0.6415 - val_accuracy: 0.8281
Epoch 9/100
1/1 [==============================] - 0s 36ms/step - loss: 0.6220 - accuracy: 0.7773 - val_loss: 0.6390 - val_accuracy: 0.8281
Epoch 10/100
1/1 [==============================] - 0s 37ms/step - loss: 0.6194 - accuracy: 0.7773 - val_loss: 0.6366 - val_accuracy: 0.8125
Epoch 11/100
1/1 [==============================] - 0s 55ms/step - loss: 0.6169 - accuracy: 0.7695 - val_loss: 0.6342 - val_accuracy: 0.8125
Epoch 12/100
1/1 [==============================] - 0s 61ms/step - loss: 0.6145 - accuracy: 0.7734 - val_loss: 0.6320 - val_accuracy: 0.8125
Epoch 13/100
1/1 [==============================] - 0s 35ms/step - loss: 0.6121 - accuracy: 0.7734 - val_loss: 0.6297 - val_accuracy: 0.8125
Epoch 14/100
1/1 [==============================] - 0s 36ms/step - loss: 0.6098 - accuracy: 0.7734 - val_loss: 0.6275 - val_accuracy: 0.8281
Epoch 15/100
1/1 [==============================] - 0s 35ms/step - loss: 0.6075 - accuracy: 0.7734 - val_loss: 0.6253 - val_accuracy: 0.8281
Epoch 16/100
1/1 [==============================] - 0s 35ms/step - loss: 0.6053 - accuracy: 0.7891 - val_loss: 0.6232 - val_accuracy: 0.8281
Epoch 17/100
1/1 [==============================] - 0s 35ms/step - loss: 0.6030 - accuracy: 0.7891 - val_loss: 0.6211 - val_accuracy: 0.8281
Epoch 18/100
1/1 [==============================] - 0s 37ms/step - loss: 0.6008 - accuracy: 0.7930 - val_loss: 0.6190 - val_accuracy: 0.8281
Epoch 19/100
1/1 [==============================] - 0s 54ms/step - loss: 0.5987 - accuracy: 0.7930 - val_loss: 0.6170 - val_accuracy: 0.8281
Epoch 20/100
1/1 [==============================] - 0s 53ms/step - loss: 0.5966 - accuracy: 0.7930 - val_loss: 0.6150 - val_accuracy: 0.8281
Epoch 21/100
1/1 [==============================] - 0s 35ms/step - loss: 0.5945 - accuracy: 0.7930 - val_loss: 0.6130 - val_accuracy: 0.8281
Epoch 22/100
1/1 [==============================] - 0s 35ms/step - loss: 0.5924 - accuracy: 0.7930 - val_loss: 0.6110 - val_accuracy: 0.8281
Epoch 23/100
1/1 [==============================] - 0s 39ms/step - loss: 0.5903 - accuracy: 0.7969 - val_loss: 0.6090 - val_accuracy: 0.8281
Epoch 24/100
1/1 [==============================] - 0s 37ms/step - loss: 0.5883 - accuracy: 0.7969 - val_loss: 0.6070 - val_accuracy: 0.8281
Epoch 25/100
1/1 [==============================] - 0s 34ms/step - loss: 0.5863 - accuracy: 0.7969 - val_loss: 0.6051 - val_accuracy: 0.8281
Epoch 26/100
1/1 [==============================] - 0s 53ms/step - loss: 0.5843 - accuracy: 0.7969 - val_loss: 0.6031 - val_accuracy: 0.8281
Epoch 27/100
1/1 [==============================] - 0s 63ms/step - loss: 0.5823 - accuracy: 0.7969 - val_loss: 0.6011 - val_accuracy: 0.8281
Epoch 28/100
1/1 [==============================] - 0s 45ms/step - loss: 0.5803 - accuracy: 0.7969 - val_loss: 0.5991 - val_accuracy: 0.8281
Epoch 29/100
1/1 [==============================] - 0s 59ms/step - loss: 0.5783 - accuracy: 0.7969 - val_loss: 0.5972 - val_accuracy: 0.8281
Epoch 30/100
1/1 [==============================] - 0s 47ms/step - loss: 0.5763 - accuracy: 0.7930 - val_loss: 0.5952 - val_accuracy: 0.8281
Epoch 31/100
1/1 [==============================] - 0s 60ms/step - loss: 0.5743 - accuracy: 0.7930 - val_loss: 0.5933 - val_accuracy: 0.8281
Epoch 32/100
1/1 [==============================] - 0s 63ms/step - loss: 0.5722 - accuracy: 0.7930 - val_loss: 0.5913 - val_accuracy: 0.8281
Epoch 33/100
1/1 [==============================] - 0s 65ms/step - loss: 0.5703 - accuracy: 0.7930 - val_loss: 0.5893 - val_accuracy: 0.8281
Epoch 34/100
1/1 [==============================] - 0s 53ms/step - loss: 0.5683 - accuracy: 0.7930 - val_loss: 0.5873 - val_accuracy: 0.8281
Epoch 35/100
1/1 [==============================] - 0s 34ms/step - loss: 0.5662 - accuracy: 0.7930 - val_loss: 0.5853 - val_accuracy: 0.8281
Epoch 36/100
1/1 [==============================] - 0s 39ms/step - loss: 0.5642 - accuracy: 0.7930 - val_loss: 0.5833 - val_accuracy: 0.8281
Epoch 37/100
1/1 [==============================] - 0s 35ms/step - loss: 0.5622 - accuracy: 0.7930 - val_loss: 0.5813 - val_accuracy: 0.8281
Epoch 38/100
1/1 [==============================] - 0s 36ms/step - loss: 0.5603 - accuracy: 0.7930 - val_loss: 0.5794 - val_accuracy: 0.8281
Epoch 39/100
1/1 [==============================] - 0s 39ms/step - loss: 0.5583 - accuracy: 0.7930 - val_loss: 0.5774 - val_accuracy: 0.8281
Epoch 40/100
1/1 [==============================] - 0s 41ms/step - loss: 0.5563 - accuracy: 0.7930 - val_loss: 0.5754 - val_accuracy: 0.8281
Epoch 41/100
1/1 [==============================] - 0s 38ms/step - loss: 0.5544 - accuracy: 0.7930 - val_loss: 0.5734 - val_accuracy: 0.8281
Epoch 42/100
1/1 [==============================] - 0s 40ms/step - loss: 0.5524 - accuracy: 0.7930 - val_loss: 0.5715 - val_accuracy: 0.8281
Epoch 43/100
1/1 [==============================] - 0s 39ms/step - loss: 0.5505 - accuracy: 0.7930 - val_loss: 0.5695 - val_accuracy: 0.8281
Epoch 44/100
1/1 [==============================] - 0s 41ms/step - loss: 0.5486 - accuracy: 0.7969 - val_loss: 0.5675 - val_accuracy: 0.8281
Epoch 45/100
1/1 [==============================] - 0s 37ms/step - loss: 0.5466 - accuracy: 0.7969 - val_loss: 0.5656 - val_accuracy: 0.8281
Epoch 46/100
1/1 [==============================] - 0s 49ms/step - loss: 0.5447 - accuracy: 0.7969 - val_loss: 0.5636 - val_accuracy: 0.8281
Epoch 47/100
1/1 [==============================] - 0s 45ms/step - loss: 0.5427 - accuracy: 0.7969 - val_loss: 0.5617 - val_accuracy: 0.8281
Epoch 48/100
1/1 [==============================] - 0s 61ms/step - loss: 0.5408 - accuracy: 0.7969 - val_loss: 0.5598 - val_accuracy: 0.8281
Epoch 49/100
1/1 [==============================] - 0s 44ms/step - loss: 0.5389 - accuracy: 0.7969 - val_loss: 0.5578 - val_accuracy: 0.8281
Epoch 50/100
1/1 [==============================] - 0s 62ms/step - loss: 0.5370 - accuracy: 0.7969 - val_loss: 0.5559 - val_accuracy: 0.8281
Epoch 51/100
1/1 [==============================] - 0s 36ms/step - loss: 0.5351 - accuracy: 0.7969 - val_loss: 0.5541 - val_accuracy: 0.8281
Epoch 52/100
1/1 [==============================] - 0s 54ms/step - loss: 0.5332 - accuracy: 0.7969 - val_loss: 0.5522 - val_accuracy: 0.8281
Epoch 53/100
1/1 [==============================] - 0s 40ms/step - loss: 0.5313 - accuracy: 0.7969 - val_loss: 0.5503 - val_accuracy: 0.8281
Epoch 54/100
1/1 [==============================] - 0s 49ms/step - loss: 0.5294 - accuracy: 0.7969 - val_loss: 0.5484 - val_accuracy: 0.8281
Epoch 55/100
1/1 [==============================] - 0s 38ms/step - loss: 0.5275 - accuracy: 0.7969 - val_loss: 0.5465 - val_accuracy: 0.8281
Epoch 56/100
1/1 [==============================] - 0s 36ms/step - loss: 0.5256 - accuracy: 0.7969 - val_loss: 0.5446 - val_accuracy: 0.8281
Epoch 57/100
1/1 [==============================] - 0s 38ms/step - loss: 0.5237 - accuracy: 0.7969 - val_loss: 0.5426 - val_accuracy: 0.8281
Epoch 58/100
1/1 [==============================] - 0s 42ms/step - loss: 0.5219 - accuracy: 0.7969 - val_loss: 0.5407 - val_accuracy: 0.8438
Epoch 59/100
1/1 [==============================] - 0s 43ms/step - loss: 0.5200 - accuracy: 0.7969 - val_loss: 0.5388 - val_accuracy: 0.8438
Epoch 60/100
1/1 [==============================] - 0s 39ms/step - loss: 0.5182 - accuracy: 0.7930 - val_loss: 0.5369 - val_accuracy: 0.8438
Epoch 61/100
1/1 [==============================] - 0s 40ms/step - loss: 0.5163 - accuracy: 0.7969 - val_loss: 0.5350 - val_accuracy: 0.8438
Epoch 62/100
1/1 [==============================] - 0s 38ms/step - loss: 0.5145 - accuracy: 0.7969 - val_loss: 0.5331 - val_accuracy: 0.8438
Epoch 63/100
1/1 [==============================] - 0s 54ms/step - loss: 0.5126 - accuracy: 0.7969 - val_loss: 0.5312 - val_accuracy: 0.8438
Epoch 64/100
1/1 [==============================] - 0s 38ms/step - loss: 0.5108 - accuracy: 0.7969 - val_loss: 0.5294 - val_accuracy: 0.8438
Epoch 65/100
1/1 [==============================] - 0s 36ms/step - loss: 0.5089 - accuracy: 0.7969 - val_loss: 0.5275 - val_accuracy: 0.8438
Epoch 66/100
1/1 [==============================] - 0s 57ms/step - loss: 0.5071 - accuracy: 0.7969 - val_loss: 0.5256 - val_accuracy: 0.8438
Epoch 67/100
1/1 [==============================] - 0s 51ms/step - loss: 0.5053 - accuracy: 0.7969 - val_loss: 0.5237 - val_accuracy: 0.8438
Epoch 68/100
1/1 [==============================] - 0s 49ms/step - loss: 0.5035 - accuracy: 0.7969 - val_loss: 0.5218 - val_accuracy: 0.8438
Epoch 69/100
1/1 [==============================] - 0s 43ms/step - loss: 0.5016 - accuracy: 0.7969 - val_loss: 0.5199 - val_accuracy: 0.8438
Epoch 70/100
1/1 [==============================] - 0s 44ms/step - loss: 0.4998 - accuracy: 0.7969 - val_loss: 0.5180 - val_accuracy: 0.8438
Epoch 71/100
1/1 [==============================] - 0s 45ms/step - loss: 0.4979 - accuracy: 0.7969 - val_loss: 0.5161 - val_accuracy: 0.8438
Epoch 72/100
1/1 [==============================] - 0s 63ms/step - loss: 0.4961 - accuracy: 0.7969 - val_loss: 0.5142 - val_accuracy: 0.8438
Epoch 73/100
1/1 [==============================] - 0s 45ms/step - loss: 0.4942 - accuracy: 0.7969 - val_loss: 0.5123 - val_accuracy: 0.8438
Epoch 74/100
1/1 [==============================] - 0s 41ms/step - loss: 0.4924 - accuracy: 0.7969 - val_loss: 0.5104 - val_accuracy: 0.8438
Epoch 75/100
1/1 [==============================] - 0s 62ms/step - loss: 0.4905 - accuracy: 0.7969 - val_loss: 0.5085 - val_accuracy: 0.8438
Epoch 76/100
1/1 [==============================] - 0s 38ms/step - loss: 0.4887 - accuracy: 0.7969 - val_loss: 0.5066 - val_accuracy: 0.8438
Epoch 77/100
1/1 [==============================] - 0s 41ms/step - loss: 0.4868 - accuracy: 0.7969 - val_loss: 0.5047 - val_accuracy: 0.8438
Epoch 78/100
1/1 [==============================] - 0s 54ms/step - loss: 0.4849 - accuracy: 0.8008 - val_loss: 0.5028 - val_accuracy: 0.8438
Epoch 79/100
1/1 [==============================] - 0s 37ms/step - loss: 0.4830 - accuracy: 0.8008 - val_loss: 0.5009 - val_accuracy: 0.8281
Epoch 80/100
1/1 [==============================] - 0s 38ms/step - loss: 0.4812 - accuracy: 0.8008 - val_loss: 0.4990 - val_accuracy: 0.8281
Epoch 81/100
1/1 [==============================] - 0s 37ms/step - loss: 0.4794 - accuracy: 0.8008 - val_loss: 0.4971 - val_accuracy: 0.8281
Epoch 82/100
1/1 [==============================] - 0s 37ms/step - loss: 0.4776 - accuracy: 0.8008 - val_loss: 0.4952 - val_accuracy: 0.8281
Epoch 83/100
1/1 [==============================] - 0s 37ms/step - loss: 0.4758 - accuracy: 0.8008 - val_loss: 0.4934 - val_accuracy: 0.8281
Epoch 84/100
1/1 [==============================] - 0s 41ms/step - loss: 0.4740 - accuracy: 0.8047 - val_loss: 0.4915 - val_accuracy: 0.8281
Epoch 85/100
1/1 [==============================] - 0s 54ms/step - loss: 0.4722 - accuracy: 0.8047 - val_loss: 0.4896 - val_accuracy: 0.8438
Epoch 86/100
1/1 [==============================] - 0s 46ms/step - loss: 0.4704 - accuracy: 0.8047 - val_loss: 0.4878 - val_accuracy: 0.8438
Epoch 87/100
1/1 [==============================] - 0s 48ms/step - loss: 0.4687 - accuracy: 0.8047 - val_loss: 0.4860 - val_accuracy: 0.8438
Epoch 88/100
1/1 [==============================] - 0s 59ms/step - loss: 0.4669 - accuracy: 0.8047 - val_loss: 0.4841 - val_accuracy: 0.8438
Epoch 89/100
1/1 [==============================] - 0s 45ms/step - loss: 0.4652 - accuracy: 0.8047 - val_loss: 0.4823 - val_accuracy: 0.8438
Epoch 90/100
1/1 [==============================] - 0s 47ms/step - loss: 0.4635 - accuracy: 0.8047 - val_loss: 0.4805 - val_accuracy: 0.8438
Epoch 91/100
1/1 [==============================] - 0s 44ms/step - loss: 0.4617 - accuracy: 0.8047 - val_loss: 0.4787 - val_accuracy: 0.8594
Epoch 92/100
1/1 [==============================] - 0s 44ms/step - loss: 0.4600 - accuracy: 0.8086 - val_loss: 0.4769 - val_accuracy: 0.8594
Epoch 93/100
1/1 [==============================] - 0s 39ms/step - loss: 0.4583 - accuracy: 0.8086 - val_loss: 0.4752 - val_accuracy: 0.8594
Epoch 94/100
1/1 [==============================] - 0s 38ms/step - loss: 0.4567 - accuracy: 0.8086 - val_loss: 0.4735 - val_accuracy: 0.8594
Epoch 95/100
1/1 [==============================] - 0s 41ms/step - loss: 0.4550 - accuracy: 0.8086 - val_loss: 0.4718 - val_accuracy: 0.8594
Epoch 96/100
1/1 [==============================] - 0s 57ms/step - loss: 0.4533 - accuracy: 0.8086 - val_loss: 0.4701 - val_accuracy: 0.8594
Epoch 97/100
1/1 [==============================] - 0s 37ms/step - loss: 0.4517 - accuracy: 0.8086 - val_loss: 0.4684 - val_accuracy: 0.8594
Epoch 98/100
1/1 [==============================] - 0s 37ms/step - loss: 0.4500 - accuracy: 0.8086 - val_loss: 0.4667 - val_accuracy: 0.8594
Epoch 99/100
1/1 [==============================] - 0s 35ms/step - loss: 0.4484 - accuracy: 0.8125 - val_loss: 0.4651 - val_accuracy: 0.8594
Epoch 100/100
1/1 [==============================] - 0s 35ms/step - loss: 0.4467 - accuracy: 0.8281 - val_loss: 0.4635 - val_accuracy: 0.8594
5.787040710449219

Stochastic Gradient Descent(SGD)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df = df.drop(['User ID', 'Gender'], axis=1)

In [ ]:
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [ ]:
X = df.iloc[:,0:2]

In [ ]:
Y = df.iloc[:,-1]

In [ ]:
X

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [ ]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
Scaler = StandardScaler()

In [ ]:
X = Scaler.fit_transform(X)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
import time

In [ ]:
model = Sequential()
model.add(Dense(10, activation="relu", input_dim = 2))
model.add(Dense(10, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 10)                30

 dense_7 (Dense)             (None, 10)                110

 dense_8 (Dense)             (None, 1)                 11

=================================================================
Total params: 151 (604.00 Byte)
Trainable params: 151 (604.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
X_train.shape

(320, 2)

In [ ]:
model.compile(loss = "binary_crossentropy", metrics = ['accuracy'])
start = time.time()
history = model.fit(X_train, Y_train, epochs = 100, batch_size=1, validation_split = 0.2)
end = time.time()
print(end-start)

Epoch 1/100
256/256 [==============================] - 1s 3ms/step - loss: 0.6490 - accuracy: 0.6953 - val_loss: 0.5367 - val_accuracy: 0.7969
Epoch 2/100
256/256 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7930 - val_loss: 0.4291 - val_accuracy: 0.8281
Epoch 3/100
256/256 [==============================] - 1s 2ms/step - loss: 0.4289 - accuracy: 0.8203 - val_loss: 0.3625 - val_accuracy: 0.8438
Epoch 4/100
256/256 [==============================] - 1s 3ms/step - loss: 0.3785 - accuracy: 0.8359 - val_loss: 0.3275 - val_accuracy: 0.8594
Epoch 5/100
256/256 [==============================] - 1s 3ms/step - loss: 0.3525 - accuracy: 0.8555 - val_loss: 0.3085 - val_accuracy: 0.8750
Epoch 6/100
256/256 [==============================] - 1s 4ms/step - loss: 0.3340 - accuracy: 0.8633 - val_loss: 0.2968 - val_accuracy: 0.8750
Epoch 7/100
256/256 [==============================] - 1s 4ms/step - loss: 0.3212 - accuracy: 0.8633 - val_loss: 0.2907 - val_accuracy: 0.8906
Epoch 8/100
256/256 [==============================] - 1s 5ms/step - loss: 0.3088 - accuracy: 0.8672 - val_loss: 0.2862 - val_accuracy: 0.8906
Epoch 9/100
256/256 [==============================] - 1s 3ms/step - loss: 0.3034 - accuracy: 0.8828 - val_loss: 0.2848 - val_accuracy: 0.8906
Epoch 10/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2929 - accuracy: 0.8906 - val_loss: 0.2861 - val_accuracy: 0.8906
Epoch 11/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2842 - accuracy: 0.8906 - val_loss: 0.2843 - val_accuracy: 0.8750
Epoch 12/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2783 - accuracy: 0.8867 - val_loss: 0.2857 - val_accuracy: 0.8750
Epoch 13/100
256/256 [==============================] - 0s 2ms/step - loss: 0.2718 - accuracy: 0.8984 - val_loss: 0.2875 - val_accuracy: 0.8750
Epoch 14/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2713 - accuracy: 0.9062 - val_loss: 0.2883 - val_accuracy: 0.8750
Epoch 15/100
256/256 [==============================] - 0s 2ms/step - loss: 0.2683 - accuracy: 0.9102 - val_loss: 0.2918 - val_accuracy: 0.8750
Epoch 16/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2682 - accuracy: 0.9062 - val_loss: 0.2976 - val_accuracy: 0.8906
Epoch 17/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2622 - accuracy: 0.9102 - val_loss: 0.3007 - val_accuracy: 0.8750
Epoch 18/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2613 - accuracy: 0.9062 - val_loss: 0.3073 - val_accuracy: 0.8906
Epoch 19/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2628 - accuracy: 0.9102 - val_loss: 0.3087 - val_accuracy: 0.8906
Epoch 20/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2609 - accuracy: 0.9219 - val_loss: 0.3107 - val_accuracy: 0.9062
Epoch 21/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2633 - accuracy: 0.9141 - val_loss: 0.3136 - val_accuracy: 0.8906
Epoch 22/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2588 - accuracy: 0.9219 - val_loss: 0.3164 - val_accuracy: 0.9062
Epoch 23/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2556 - accuracy: 0.9219 - val_loss: 0.3160 - val_accuracy: 0.9062
Epoch 24/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2550 - accuracy: 0.9180 - val_loss: 0.3229 - val_accuracy: 0.8906
Epoch 25/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2560 - accuracy: 0.9180 - val_loss: 0.3222 - val_accuracy: 0.8906
Epoch 26/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2551 - accuracy: 0.9219 - val_loss: 0.3228 - val_accuracy: 0.8906
Epoch 27/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2576 - accuracy: 0.9180 - val_loss: 0.3282 - val_accuracy: 0.8906
Epoch 28/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2556 - accuracy: 0.9219 - val_loss: 0.3369 - val_accuracy: 0.8906
Epoch 29/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2612 - accuracy: 0.9258 - val_loss: 0.3408 - val_accuracy: 0.8906
Epoch 30/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2591 - accuracy: 0.9219 - val_loss: 0.3374 - val_accuracy: 0.8906
Epoch 31/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2569 - accuracy: 0.9258 - val_loss: 0.3369 - val_accuracy: 0.8906
Epoch 32/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2585 - accuracy: 0.9219 - val_loss: 0.3409 - val_accuracy: 0.8906
Epoch 33/100
256/256 [==============================] - 0s 2ms/step - loss: 0.2566 - accuracy: 0.9258 - val_loss: 0.3403 - val_accuracy: 0.8906
Epoch 34/100
256/256 [==============================] - 0s 2ms/step - loss: 0.2524 - accuracy: 0.9258 - val_loss: 0.3397 - val_accuracy: 0.8906
Epoch 35/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2585 - accuracy: 0.9219 - val_loss: 0.3378 - val_accuracy: 0.8906
Epoch 36/100
256/256 [==============================] - 0s 2ms/step - loss: 0.2572 - accuracy: 0.9219 - val_loss: 0.3405 - val_accuracy: 0.8906
Epoch 37/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2553 - accuracy: 0.9219 - val_loss: 0.3390 - val_accuracy: 0.8906
Epoch 38/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2515 - accuracy: 0.9258 - val_loss: 0.3398 - val_accuracy: 0.8906
Epoch 39/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2556 - accuracy: 0.9219 - val_loss: 0.3426 - val_accuracy: 0.8906
Epoch 40/100
256/256 [==============================] - 0s 2ms/step - loss: 0.2554 - accuracy: 0.9219 - val_loss: 0.3429 - val_accuracy: 0.8906
Epoch 41/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2569 - accuracy: 0.9180 - val_loss: 0.3483 - val_accuracy: 0.8906
Epoch 42/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2616 - accuracy: 0.9141 - val_loss: 0.3484 - val_accuracy: 0.8906
Epoch 43/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2535 - accuracy: 0.9258 - val_loss: 0.3517 - val_accuracy: 0.8906
Epoch 44/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2595 - accuracy: 0.9219 - val_loss: 0.3575 - val_accuracy: 0.8906
Epoch 45/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2566 - accuracy: 0.9258 - val_loss: 0.3592 - val_accuracy: 0.8906
Epoch 46/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2567 - accuracy: 0.9258 - val_loss: 0.3618 - val_accuracy: 0.8906
Epoch 47/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2606 - accuracy: 0.9180 - val_loss: 0.3605 - val_accuracy: 0.8906
Epoch 48/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2599 - accuracy: 0.9219 - val_loss: 0.3612 - val_accuracy: 0.8906
Epoch 49/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2592 - accuracy: 0.9258 - val_loss: 0.3568 - val_accuracy: 0.8906
Epoch 50/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2573 - accuracy: 0.9258 - val_loss: 0.3591 - val_accuracy: 0.8906
Epoch 51/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2578 - accuracy: 0.9219 - val_loss: 0.3597 - val_accuracy: 0.8906
Epoch 52/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2566 - accuracy: 0.9258 - val_loss: 0.3595 - val_accuracy: 0.8906
Epoch 53/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2539 - accuracy: 0.9258 - val_loss: 0.3600 - val_accuracy: 0.8906
Epoch 54/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2584 - accuracy: 0.9219 - val_loss: 0.3647 - val_accuracy: 0.8906
Epoch 55/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2601 - accuracy: 0.9258 - val_loss: 0.3656 - val_accuracy: 0.8906
Epoch 56/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2603 - accuracy: 0.9219 - val_loss: 0.3664 - val_accuracy: 0.8906
Epoch 57/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2578 - accuracy: 0.9258 - val_loss: 0.3669 - val_accuracy: 0.8906
Epoch 58/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2540 - accuracy: 0.9219 - val_loss: 0.3700 - val_accuracy: 0.8906
Epoch 59/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2571 - accuracy: 0.9180 - val_loss: 0.3735 - val_accuracy: 0.8906
Epoch 60/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2664 - accuracy: 0.9219 - val_loss: 0.3748 - val_accuracy: 0.8906
Epoch 61/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2584 - accuracy: 0.9219 - val_loss: 0.3776 - val_accuracy: 0.8906
Epoch 62/100
256/256 [==============================] - 0s 2ms/step - loss: 0.2605 - accuracy: 0.9258 - val_loss: 0.3781 - val_accuracy: 0.8906
Epoch 63/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2614 - accuracy: 0.9180 - val_loss: 0.3787 - val_accuracy: 0.8906
Epoch 64/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2636 - accuracy: 0.9219 - val_loss: 0.3809 - val_accuracy: 0.8906
Epoch 65/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2600 - accuracy: 0.9297 - val_loss: 0.3814 - val_accuracy: 0.8906
Epoch 66/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2603 - accuracy: 0.9219 - val_loss: 0.3847 - val_accuracy: 0.8906
Epoch 67/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2603 - accuracy: 0.9219 - val_loss: 0.3843 - val_accuracy: 0.8906
Epoch 68/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2614 - accuracy: 0.9180 - val_loss: 0.3870 - val_accuracy: 0.8906
Epoch 69/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2592 - accuracy: 0.9258 - val_loss: 0.3891 - val_accuracy: 0.8906
Epoch 70/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2622 - accuracy: 0.9219 - val_loss: 0.3903 - val_accuracy: 0.8906
Epoch 71/100
256/256 [==============================] - 0s 2ms/step - loss: 0.2619 - accuracy: 0.9258 - val_loss: 0.3912 - val_accuracy: 0.8906
Epoch 72/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2621 - accuracy: 0.9258 - val_loss: 0.3920 - val_accuracy: 0.8906
Epoch 73/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2628 - accuracy: 0.9258 - val_loss: 0.3898 - val_accuracy: 0.8906
Epoch 74/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2642 - accuracy: 0.9219 - val_loss: 0.4002 - val_accuracy: 0.8906
Epoch 75/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2644 - accuracy: 0.9219 - val_loss: 0.3946 - val_accuracy: 0.8906
Epoch 76/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2573 - accuracy: 0.9180 - val_loss: 0.3941 - val_accuracy: 0.8906
Epoch 77/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2612 - accuracy: 0.9297 - val_loss: 0.3925 - val_accuracy: 0.8906
Epoch 78/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2602 - accuracy: 0.9258 - val_loss: 0.3928 - val_accuracy: 0.8906
Epoch 79/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2700 - accuracy: 0.9219 - val_loss: 0.4045 - val_accuracy: 0.8906
Epoch 80/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2725 - accuracy: 0.9180 - val_loss: 0.4073 - val_accuracy: 0.8906
Epoch 81/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2685 - accuracy: 0.9258 - val_loss: 0.4063 - val_accuracy: 0.8906
Epoch 82/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2660 - accuracy: 0.9297 - val_loss: 0.4041 - val_accuracy: 0.8906
Epoch 83/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2685 - accuracy: 0.9258 - val_loss: 0.4031 - val_accuracy: 0.8906
Epoch 84/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2623 - accuracy: 0.9258 - val_loss: 0.4126 - val_accuracy: 0.8906
Epoch 85/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2702 - accuracy: 0.9297 - val_loss: 0.4180 - val_accuracy: 0.8906
Epoch 86/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2691 - accuracy: 0.9258 - val_loss: 0.4121 - val_accuracy: 0.8906
Epoch 87/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2665 - accuracy: 0.9297 - val_loss: 0.4024 - val_accuracy: 0.8906
Epoch 88/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2682 - accuracy: 0.9258 - val_loss: 0.4033 - val_accuracy: 0.8906
Epoch 89/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2671 - accuracy: 0.9297 - val_loss: 0.4133 - val_accuracy: 0.8906
Epoch 90/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2750 - accuracy: 0.9219 - val_loss: 0.4190 - val_accuracy: 0.8906
Epoch 91/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2790 - accuracy: 0.9219 - val_loss: 0.4195 - val_accuracy: 0.8906
Epoch 92/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2778 - accuracy: 0.9258 - val_loss: 0.4126 - val_accuracy: 0.8906
Epoch 93/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2733 - accuracy: 0.9219 - val_loss: 0.4153 - val_accuracy: 0.8906
Epoch 94/100
256/256 [==============================] - 0s 2ms/step - loss: 0.2713 - accuracy: 0.9297 - val_loss: 0.4081 - val_accuracy: 0.8906
Epoch 95/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2643 - accuracy: 0.9297 - val_loss: 0.4109 - val_accuracy: 0.8906
Epoch 96/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2703 - accuracy: 0.9258 - val_loss: 0.4197 - val_accuracy: 0.8906
Epoch 97/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2679 - accuracy: 0.9297 - val_loss: 0.4197 - val_accuracy: 0.8906
Epoch 98/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2673 - accuracy: 0.9258 - val_loss: 0.4209 - val_accuracy: 0.8906
Epoch 99/100
256/256 [==============================] - 1s 3ms/step - loss: 0.2640 - accuracy: 0.9258 - val_loss: 0.4313 - val_accuracy: 0.8906
Epoch 100/100
256/256 [==============================] - 1s 2ms/step - loss: 0.2782 - accuracy: 0.9219 - val_loss: 0.4301 - val_accuracy: 0.8906
62.827590465545654

Mini Batch Gradient Descent

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df = df.drop(['User ID', 'Gender'], axis=1)

In [ ]:
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [ ]:
X = df.iloc[:,0:2]

In [ ]:
Y = df.iloc[:,-1]

In [ ]:
X

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [ ]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
Scaler = StandardScaler()

In [ ]:
X = Scaler.fit_transform(X)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
import time

In [ ]:
model = Sequential()
model.add(Dense(10, activation="relu", input_dim = 2))
model.add(Dense(10, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 10)                30

 dense_10 (Dense)            (None, 10)                110

 dense_11 (Dense)            (None, 1)                 11

=================================================================
Total params: 151 (604.00 Byte)
Trainable params: 151 (604.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
X_train.shape

(320, 2)

In [ ]:
model.compile(loss = "binary_crossentropy", metrics = ['accuracy'])
start = time.time()
history = model.fit(X_train, Y_train, epochs = 100, batch_size=250, validation_split=0.2)
end = time.time()
print(end-start)

Epoch 1/100
2/2 [==============================] - 1s 181ms/step - loss: 0.6649 - accuracy: 0.3711 - val_loss: 0.6804 - val_accuracy: 0.3125
Epoch 2/100
2/2 [==============================] - 0s 37ms/step - loss: 0.6566 - accuracy: 0.3750 - val_loss: 0.6756 - val_accuracy: 0.3438
Epoch 3/100
2/2 [==============================] - 0s 32ms/step - loss: 0.6511 - accuracy: 0.3984 - val_loss: 0.6704 - val_accuracy: 0.4375
Epoch 4/100
2/2 [==============================] - 0s 30ms/step - loss: 0.6463 - accuracy: 0.4766 - val_loss: 0.6669 - val_accuracy: 0.5469
Epoch 5/100
2/2 [==============================] - 0s 31ms/step - loss: 0.6432 - accuracy: 0.5195 - val_loss: 0.6636 - val_accuracy: 0.5781
Epoch 6/100
2/2 [==============================] - 0s 31ms/step - loss: 0.6403 - accuracy: 0.5859 - val_loss: 0.6621 - val_accuracy: 0.5781
Epoch 7/100
2/2 [==============================] - 0s 48ms/step - loss: 0.6382 - accuracy: 0.5938 - val_loss: 0.6594 - val_accuracy: 0.6250
Epoch 8/100
2/2 [==============================] - 0s 33ms/step - loss: 0.6356 - accuracy: 0.6055 - val_loss: 0.6578 - val_accuracy: 0.6250
Epoch 9/100
2/2 [==============================] - 0s 34ms/step - loss: 0.6333 - accuracy: 0.6094 - val_loss: 0.6553 - val_accuracy: 0.6406
Epoch 10/100
2/2 [==============================] - 0s 52ms/step - loss: 0.6307 - accuracy: 0.6289 - val_loss: 0.6532 - val_accuracy: 0.6406
Epoch 11/100
2/2 [==============================] - 0s 32ms/step - loss: 0.6281 - accuracy: 0.6445 - val_loss: 0.6504 - val_accuracy: 0.6875
Epoch 12/100
2/2 [==============================] - 0s 32ms/step - loss: 0.6251 - accuracy: 0.6562 - val_loss: 0.6470 - val_accuracy: 0.6875
Epoch 13/100
2/2 [==============================] - 0s 31ms/step - loss: 0.6221 - accuracy: 0.6680 - val_loss: 0.6444 - val_accuracy: 0.7031
Epoch 14/100
2/2 [==============================] - 0s 32ms/step - loss: 0.6197 - accuracy: 0.6797 - val_loss: 0.6433 - val_accuracy: 0.7031
Epoch 15/100
2/2 [==============================] - 0s 34ms/step - loss: 0.6180 - accuracy: 0.6797 - val_loss: 0.6400 - val_accuracy: 0.7031
Epoch 16/100
2/2 [==============================] - 0s 30ms/step - loss: 0.6150 - accuracy: 0.6797 - val_loss: 0.6381 - val_accuracy: 0.7188
Epoch 17/100
2/2 [==============================] - 0s 39ms/step - loss: 0.6126 - accuracy: 0.6953 - val_loss: 0.6356 - val_accuracy: 0.7188
Epoch 18/100
2/2 [==============================] - 0s 32ms/step - loss: 0.6105 - accuracy: 0.7070 - val_loss: 0.6332 - val_accuracy: 0.7344
Epoch 19/100
2/2 [==============================] - 0s 39ms/step - loss: 0.6087 - accuracy: 0.7148 - val_loss: 0.6312 - val_accuracy: 0.7344
Epoch 20/100
2/2 [==============================] - 0s 31ms/step - loss: 0.6070 - accuracy: 0.7148 - val_loss: 0.6287 - val_accuracy: 0.7344
Epoch 21/100
2/2 [==============================] - 0s 33ms/step - loss: 0.6048 - accuracy: 0.7305 - val_loss: 0.6258 - val_accuracy: 0.7500
Epoch 22/100
2/2 [==============================] - 0s 58ms/step - loss: 0.6024 - accuracy: 0.7422 - val_loss: 0.6231 - val_accuracy: 0.7500
Epoch 23/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5999 - accuracy: 0.7539 - val_loss: 0.6215 - val_accuracy: 0.7656
Epoch 24/100
2/2 [==============================] - 0s 53ms/step - loss: 0.5983 - accuracy: 0.7578 - val_loss: 0.6195 - val_accuracy: 0.7656
Epoch 25/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5963 - accuracy: 0.7578 - val_loss: 0.6177 - val_accuracy: 0.7656
Epoch 26/100
2/2 [==============================] - 0s 42ms/step - loss: 0.5952 - accuracy: 0.7695 - val_loss: 0.6162 - val_accuracy: 0.7656
Epoch 27/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5935 - accuracy: 0.7695 - val_loss: 0.6152 - val_accuracy: 0.7812
Epoch 28/100
2/2 [==============================] - 0s 60ms/step - loss: 0.5921 - accuracy: 0.7773 - val_loss: 0.6132 - val_accuracy: 0.7812
Epoch 29/100
2/2 [==============================] - 0s 40ms/step - loss: 0.5902 - accuracy: 0.7773 - val_loss: 0.6120 - val_accuracy: 0.7969
Epoch 30/100
2/2 [==============================] - 0s 51ms/step - loss: 0.5890 - accuracy: 0.7812 - val_loss: 0.6112 - val_accuracy: 0.7812
Epoch 31/100
2/2 [==============================] - 0s 34ms/step - loss: 0.5875 - accuracy: 0.7812 - val_loss: 0.6087 - val_accuracy: 0.7969
Epoch 32/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5857 - accuracy: 0.7852 - val_loss: 0.6059 - val_accuracy: 0.7969
Epoch 33/100
2/2 [==============================] - 0s 32ms/step - loss: 0.5831 - accuracy: 0.7852 - val_loss: 0.6045 - val_accuracy: 0.7969
Epoch 34/100
2/2 [==============================] - 0s 34ms/step - loss: 0.5812 - accuracy: 0.7852 - val_loss: 0.6033 - val_accuracy: 0.7969
Epoch 35/100
2/2 [==============================] - 0s 31ms/step - loss: 0.5798 - accuracy: 0.7852 - val_loss: 0.6018 - val_accuracy: 0.7969
Epoch 36/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5778 - accuracy: 0.7852 - val_loss: 0.5999 - val_accuracy: 0.7969
Epoch 37/100
2/2 [==============================] - 0s 32ms/step - loss: 0.5757 - accuracy: 0.7852 - val_loss: 0.5991 - val_accuracy: 0.7969
Epoch 38/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5740 - accuracy: 0.7852 - val_loss: 0.5966 - val_accuracy: 0.7969
Epoch 39/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5719 - accuracy: 0.7852 - val_loss: 0.5950 - val_accuracy: 0.7969
Epoch 40/100
2/2 [==============================] - 0s 32ms/step - loss: 0.5699 - accuracy: 0.7852 - val_loss: 0.5941 - val_accuracy: 0.7969
Epoch 41/100
2/2 [==============================] - 0s 61ms/step - loss: 0.5682 - accuracy: 0.7852 - val_loss: 0.5922 - val_accuracy: 0.7969
Epoch 42/100
2/2 [==============================] - 0s 39ms/step - loss: 0.5659 - accuracy: 0.7891 - val_loss: 0.5893 - val_accuracy: 0.7969
Epoch 43/100
2/2 [==============================] - 0s 40ms/step - loss: 0.5631 - accuracy: 0.7930 - val_loss: 0.5881 - val_accuracy: 0.7969
Epoch 44/100
2/2 [==============================] - 0s 47ms/step - loss: 0.5613 - accuracy: 0.7930 - val_loss: 0.5864 - val_accuracy: 0.7969
Epoch 45/100
2/2 [==============================] - 0s 58ms/step - loss: 0.5594 - accuracy: 0.7891 - val_loss: 0.5850 - val_accuracy: 0.7969
Epoch 46/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5576 - accuracy: 0.7891 - val_loss: 0.5822 - val_accuracy: 0.7812
Epoch 47/100
2/2 [==============================] - 0s 32ms/step - loss: 0.5554 - accuracy: 0.8242 - val_loss: 0.5798 - val_accuracy: 0.7969
Epoch 48/100
2/2 [==============================] - 0s 34ms/step - loss: 0.5532 - accuracy: 0.8242 - val_loss: 0.5774 - val_accuracy: 0.8125
Epoch 49/100
2/2 [==============================] - 0s 34ms/step - loss: 0.5508 - accuracy: 0.8203 - val_loss: 0.5751 - val_accuracy: 0.8281
Epoch 50/100
2/2 [==============================] - 0s 52ms/step - loss: 0.5487 - accuracy: 0.8203 - val_loss: 0.5744 - val_accuracy: 0.8438
Epoch 51/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5470 - accuracy: 0.8281 - val_loss: 0.5719 - val_accuracy: 0.8281
Epoch 52/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5454 - accuracy: 0.8203 - val_loss: 0.5699 - val_accuracy: 0.8438
Epoch 53/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5434 - accuracy: 0.8281 - val_loss: 0.5679 - val_accuracy: 0.8438
Epoch 54/100
2/2 [==============================] - 0s 36ms/step - loss: 0.5415 - accuracy: 0.8281 - val_loss: 0.5660 - val_accuracy: 0.8594
Epoch 55/100
2/2 [==============================] - 0s 34ms/step - loss: 0.5399 - accuracy: 0.8398 - val_loss: 0.5644 - val_accuracy: 0.8594
Epoch 56/100
2/2 [==============================] - 0s 35ms/step - loss: 0.5386 - accuracy: 0.8477 - val_loss: 0.5624 - val_accuracy: 0.8594
Epoch 57/100
2/2 [==============================] - 0s 35ms/step - loss: 0.5363 - accuracy: 0.8477 - val_loss: 0.5605 - val_accuracy: 0.8594
Epoch 58/100
2/2 [==============================] - 0s 48ms/step - loss: 0.5341 - accuracy: 0.8477 - val_loss: 0.5590 - val_accuracy: 0.8594
Epoch 59/100
2/2 [==============================] - 0s 48ms/step - loss: 0.5322 - accuracy: 0.8477 - val_loss: 0.5579 - val_accuracy: 0.8594
Epoch 60/100
2/2 [==============================] - 0s 37ms/step - loss: 0.5308 - accuracy: 0.8555 - val_loss: 0.5557 - val_accuracy: 0.8594
Epoch 61/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5283 - accuracy: 0.8516 - val_loss: 0.5546 - val_accuracy: 0.8594
Epoch 62/100
2/2 [==============================] - 0s 58ms/step - loss: 0.5265 - accuracy: 0.8555 - val_loss: 0.5520 - val_accuracy: 0.8594
Epoch 63/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5241 - accuracy: 0.8516 - val_loss: 0.5500 - val_accuracy: 0.8594
Epoch 64/100
2/2 [==============================] - 0s 63ms/step - loss: 0.5226 - accuracy: 0.8711 - val_loss: 0.5492 - val_accuracy: 0.8594
Epoch 65/100
2/2 [==============================] - 0s 40ms/step - loss: 0.5209 - accuracy: 0.8750 - val_loss: 0.5470 - val_accuracy: 0.8594
Epoch 66/100
2/2 [==============================] - 0s 57ms/step - loss: 0.5189 - accuracy: 0.8711 - val_loss: 0.5446 - val_accuracy: 0.8750
Epoch 67/100
2/2 [==============================] - 0s 34ms/step - loss: 0.5168 - accuracy: 0.8711 - val_loss: 0.5430 - val_accuracy: 0.8750
Epoch 68/100
2/2 [==============================] - 0s 36ms/step - loss: 0.5150 - accuracy: 0.8711 - val_loss: 0.5409 - val_accuracy: 0.8750
Epoch 69/100
2/2 [==============================] - 0s 32ms/step - loss: 0.5131 - accuracy: 0.8906 - val_loss: 0.5397 - val_accuracy: 0.8750
Epoch 70/100
2/2 [==============================] - 0s 32ms/step - loss: 0.5112 - accuracy: 0.8867 - val_loss: 0.5378 - val_accuracy: 0.8750
Epoch 71/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5093 - accuracy: 0.8867 - val_loss: 0.5354 - val_accuracy: 0.8750
Epoch 72/100
2/2 [==============================] - 0s 32ms/step - loss: 0.5071 - accuracy: 0.9023 - val_loss: 0.5338 - val_accuracy: 0.8750
Epoch 73/100
2/2 [==============================] - 0s 32ms/step - loss: 0.5049 - accuracy: 0.9023 - val_loss: 0.5321 - val_accuracy: 0.8750
Epoch 74/100
2/2 [==============================] - 0s 36ms/step - loss: 0.5031 - accuracy: 0.8984 - val_loss: 0.5308 - val_accuracy: 0.8750
Epoch 75/100
2/2 [==============================] - 0s 33ms/step - loss: 0.5011 - accuracy: 0.8984 - val_loss: 0.5282 - val_accuracy: 0.8750
Epoch 76/100
2/2 [==============================] - 0s 35ms/step - loss: 0.4987 - accuracy: 0.9062 - val_loss: 0.5262 - val_accuracy: 0.8906
Epoch 77/100
2/2 [==============================] - 0s 36ms/step - loss: 0.4966 - accuracy: 0.9062 - val_loss: 0.5252 - val_accuracy: 0.8906
Epoch 78/100
2/2 [==============================] - 0s 32ms/step - loss: 0.4951 - accuracy: 0.9062 - val_loss: 0.5224 - val_accuracy: 0.8906
Epoch 79/100
2/2 [==============================] - 0s 51ms/step - loss: 0.4925 - accuracy: 0.9102 - val_loss: 0.5205 - val_accuracy: 0.8906
Epoch 80/100
2/2 [==============================] - 0s 43ms/step - loss: 0.4904 - accuracy: 0.9180 - val_loss: 0.5178 - val_accuracy: 0.8906
Epoch 81/100
2/2 [==============================] - 0s 57ms/step - loss: 0.4882 - accuracy: 0.9141 - val_loss: 0.5159 - val_accuracy: 0.8906
Epoch 82/100
2/2 [==============================] - 0s 58ms/step - loss: 0.4862 - accuracy: 0.9102 - val_loss: 0.5138 - val_accuracy: 0.8906
Epoch 83/100
2/2 [==============================] - 0s 50ms/step - loss: 0.4844 - accuracy: 0.9141 - val_loss: 0.5133 - val_accuracy: 0.9062
Epoch 84/100
2/2 [==============================] - 0s 33ms/step - loss: 0.4837 - accuracy: 0.9219 - val_loss: 0.5115 - val_accuracy: 0.9062
Epoch 85/100
2/2 [==============================] - 0s 36ms/step - loss: 0.4823 - accuracy: 0.9219 - val_loss: 0.5100 - val_accuracy: 0.8906
Epoch 86/100
2/2 [==============================] - 0s 49ms/step - loss: 0.4803 - accuracy: 0.9180 - val_loss: 0.5082 - val_accuracy: 0.8906
Epoch 87/100
2/2 [==============================] - 0s 33ms/step - loss: 0.4785 - accuracy: 0.9102 - val_loss: 0.5062 - val_accuracy: 0.8906
Epoch 88/100
2/2 [==============================] - 0s 36ms/step - loss: 0.4766 - accuracy: 0.9102 - val_loss: 0.5049 - val_accuracy: 0.8906
Epoch 89/100
2/2 [==============================] - 0s 31ms/step - loss: 0.4749 - accuracy: 0.9102 - val_loss: 0.5031 - val_accuracy: 0.8906
Epoch 90/100
2/2 [==============================] - 0s 32ms/step - loss: 0.4735 - accuracy: 0.9102 - val_loss: 0.5011 - val_accuracy: 0.8906
Epoch 91/100
2/2 [==============================] - 0s 32ms/step - loss: 0.4715 - accuracy: 0.9102 - val_loss: 0.4990 - val_accuracy: 0.8906
Epoch 92/100
2/2 [==============================] - 0s 32ms/step - loss: 0.4695 - accuracy: 0.9102 - val_loss: 0.4972 - val_accuracy: 0.8906
Epoch 93/100
2/2 [==============================] - 0s 32ms/step - loss: 0.4674 - accuracy: 0.9102 - val_loss: 0.4949 - val_accuracy: 0.8906
Epoch 94/100
2/2 [==============================] - 0s 33ms/step - loss: 0.4657 - accuracy: 0.9141 - val_loss: 0.4928 - val_accuracy: 0.8906
Epoch 95/100
2/2 [==============================] - 0s 32ms/step - loss: 0.4636 - accuracy: 0.9023 - val_loss: 0.4907 - val_accuracy: 0.8906
Epoch 96/100
2/2 [==============================] - 0s 34ms/step - loss: 0.4615 - accuracy: 0.9023 - val_loss: 0.4898 - val_accuracy: 0.8906
Epoch 97/100
2/2 [==============================] - 0s 41ms/step - loss: 0.4601 - accuracy: 0.9023 - val_loss: 0.4882 - val_accuracy: 0.8906
Epoch 98/100
2/2 [==============================] - 0s 34ms/step - loss: 0.4585 - accuracy: 0.9102 - val_loss: 0.4875 - val_accuracy: 0.8906
Epoch 99/100
2/2 [==============================] - 0s 44ms/step - loss: 0.4571 - accuracy: 0.9141 - val_loss: 0.4861 - val_accuracy: 0.8906
Epoch 100/100
2/2 [==============================] - 0s 57ms/step - loss: 0.4556 - accuracy: 0.9023 - val_loss: 0.4858 - val_accuracy: 0.8906
10.944060564041138